using FirebirdSql.Data.FirebirdClient;
using FireHook.Models;

namespace FireHook.Coordination;

public sealed class EventCoordinationTable(string connectionString)
{
    private const string CreateEventsTable = """
        EXECUTE BLOCK AS BEGIN
          IF (NOT EXISTS (
            SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'FIREHOOK_EVENTS'
          )) THEN
          EXECUTE STATEMENT '
            CREATE TABLE FIREHOOK_EVENTS (
              ID         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              EVENT_NAME VARCHAR(128)  NOT NULL,
              PAYLOAD    BLOB SUB_TYPE TEXT,
              FIRED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
              PROCESSED  SMALLINT DEFAULT 0 NOT NULL
            )';
        END
        """;

    private const string CreateTrigger = """
        EXECUTE BLOCK AS BEGIN
          IF (NOT EXISTS (
            SELECT 1 FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'FIREHOOK_POST_EVENT'
          )) THEN
          EXECUTE STATEMENT '
            CREATE TRIGGER FIREHOOK_POST_EVENT
              AFTER INSERT ON FIREHOOK_EVENTS
              AS BEGIN
                POST_EVENT NEW.EVENT_NAME;
              END';
        END
        """;

    public async Task InsertEventAsync(string eventName, string? payload, CancellationToken ct = default)
    {
        await using var conn = new FbConnection(connectionString);
        await conn.OpenAsync(ct);
        await using var tx = await conn.BeginTransactionAsync(ct);

        await using var cmd = new FbCommand(
            "INSERT INTO FIREHOOK_EVENTS (EVENT_NAME, PAYLOAD) VALUES (@name, @payload)", conn, tx);
        cmd.Parameters.AddWithValue("@name", eventName);
        cmd.Parameters.Add(new FbParameter("@payload", FbDbType.Text) { Value = (object?)payload ?? DBNull.Value });
        await cmd.ExecuteNonQueryAsync(ct);

        await tx.CommitAsync(ct);
    }

    public async Task FireDirectAsync(string eventName, CancellationToken ct = default)
    {
        await using var conn = new FbConnection(connectionString);
        await conn.OpenAsync(ct);

        // EXECUTE BLOCK with an input parameter avoids string interpolation
        const string sql = """
            EXECUTE BLOCK (NAME VARCHAR(128) = ?)
            AS BEGIN
              POST_EVENT NAME;
            END
            """;

        await using var cmd = new FbCommand(sql, conn);
        cmd.Parameters.Add(new FbParameter { Value = eventName });
        await cmd.ExecuteNonQueryAsync(ct);
    }

    public async Task EnsureSchemaAsync(CancellationToken ct = default)
    {
        await using var conn = new FbConnection(connectionString);
        await conn.OpenAsync(ct);

        await using var tx = await conn.BeginTransactionAsync(ct);

        await ExecuteAsync(conn, tx, CreateEventsTable, ct);
        await ExecuteAsync(conn, tx, CreateTrigger, ct);

        await tx.CommitAsync(ct);
    }

    public async Task<IReadOnlyList<FireHookEvent>> FetchPendingAsync(string eventName, CancellationToken ct = default)
    {
        await using var conn = new FbConnection(connectionString);
        await conn.OpenAsync(ct);

        const string sql = """
            SELECT ID, EVENT_NAME, PAYLOAD, FIRED_AT
            FROM FIREHOOK_EVENTS
            WHERE EVENT_NAME = @name AND PROCESSED = 0
            ORDER BY ID
            """;

        await using var cmd = new FbCommand(sql, conn);
        cmd.Parameters.AddWithValue("@name", eventName);

        var results = new List<FireHookEvent>();
        await using var reader = await cmd.ExecuteReaderAsync(ct);
        while (await reader.ReadAsync(ct))
        {
            results.Add(new FireHookEvent
            {
                Id = reader.GetInt64(0),
                EventName = reader.GetString(1),
                Payload = reader.IsDBNull(2) ? null : reader.GetString(2),
                FiredAt = reader.GetDateTime(3)
            });
        }

        return results;
    }

    public async Task MarkProcessedAsync(long id, CancellationToken ct = default) =>
        await SetProcessedFlagAsync(id, 1, ct);

    public async Task MarkDeadLetterAsync(long id, CancellationToken ct = default) =>
        await SetProcessedFlagAsync(id, -1, ct);

    private async Task SetProcessedFlagAsync(long id, short flag, CancellationToken ct)
    {
        await using var conn = new FbConnection(connectionString);
        await conn.OpenAsync(ct);

        await using var cmd = new FbCommand(
            "UPDATE FIREHOOK_EVENTS SET PROCESSED = @flag WHERE ID = @id", conn);
        cmd.Parameters.AddWithValue("@flag", flag);
        cmd.Parameters.AddWithValue("@id", id);
        await cmd.ExecuteNonQueryAsync(ct);
    }

    private static async Task ExecuteAsync(FbConnection conn, FbTransaction tx, string sql, CancellationToken ct)
    {
        await using var cmd = new FbCommand(sql, conn, tx);
        await cmd.ExecuteNonQueryAsync(ct);
    }
}
